# Generated by Django 4.0.4 on 2022-05-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='owner',
        ),
    ]
