# Generated by Django 4.0.4 on 2022-05-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_remove_thing_description_remove_thing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
