# Generated by Django 4.0.4 on 2022-05-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadealz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
