# Generated by Django 4.0.4 on 2022-05-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadealz', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
